export const SESSION_IDLE_TIMEOUT_MS = 30 * 60 * 1000 // 30 minutes
export const MAX_CONCURRENT_SESSIONS = 5
export const TERMINAL_DEFAULT_COLS = 80
export const TERMINAL_DEFAULT_ROWS = 24
export const TERMINAL_WS_RECONNECT_BASE_DELAY_MS = 1000
export const TERMINAL_WS_MAX_RECONNECT_RETRIES = 5
