import * as fs from 'fs'
import * as path from 'path'

jest.mock('fs')
jest.mock('../src/logger')
jest.mock('../src/project-dir', () => ({
  getAwsDir: (projectDir: string) =>
    path.join(projectDir, '.ai-support-agent', 'aws'),
}))

import {
  getProfileName,
  generateAwsConfig,
  writeAwsConfig,
  generateAwsCredentials,
  writeAwsCredentials,
  cleanupAwsCredentials,
  cleanupStaleAwsCredentials,
  buildAwsProfileEnv,
} from '../src/aws-profile'
import { logger } from '../src/logger'
import type { AwsCredentials, ProjectConfigResponse } from '../src/types'

type AwsAccount = NonNullable<ProjectConfigResponse['aws']>['accounts'][number]

const mockedFs = fs as jest.Mocked<typeof fs>

describe('aws-profile', () => {
  beforeEach(() => {
    jest.clearAllMocks()
  })

  describe('getProfileName', () => {
    it('should return projectCode-accountName format with string', () => {
      expect(getProfileName('MBC_01', 'dev')).toBe('MBC_01-dev')
    })

    it('should handle special characters in names', () => {
      expect(getProfileName('PROJ_A', 'staging-us')).toBe('PROJ_A-staging-us')
    })

    it('should use profileName when provided in account object', () => {
      expect(getProfileName('MBC_01', { name: 'Production', profileName: 'prod' })).toBe('MBC_01-prod')
    })

    it('should fall back to name when profileName is not provided', () => {
      expect(getProfileName('MBC_01', { name: 'dev-account' })).toBe('MBC_01-dev-account')
    })

    it('should fall back to name when profileName is empty', () => {
      expect(getProfileName('MBC_01', { name: 'staging', profileName: '' })).toBe('MBC_01-staging')
    })
  })

  describe('generateAwsConfig', () => {
    it('should generate config for a single access_key account', () => {
      const accounts: AwsAccount[] = [
        {
          id: 'acc-1',
          name: 'dev',
          region: 'ap-northeast-1',
          accountId: '123456789012',
          auth: { method: 'access_key' },
          isDefault: true,
        },
      ]

      const result = generateAwsConfig('MBC_01', accounts)

      expect(result).toContain('# Auto-generated by ai-support-agent for project: MBC_01')
      expect(result).toContain('# Do not edit manually')
      expect(result).toContain('[profile MBC_01-dev]')
      expect(result).toContain('region = ap-northeast-1')
      // access_key method should not have SSO fields
      expect(result).not.toContain('sso_start_url')
      expect(result).not.toContain('sso_region')
      expect(result).not.toContain('sso_account_id')
      expect(result).not.toContain('sso_role_name')
    })

    it('should generate config for a single sso account', () => {
      const accounts: AwsAccount[] = [
        {
          id: 'acc-2',
          name: 'prod',
          region: 'us-east-1',
          accountId: '987654321098',
          auth: {
            method: 'sso',
            startUrl: 'https://my-sso.awsapps.com/start',
            ssoRegion: 'us-east-1',
            permissionSetName: 'AdministratorAccess',
          },
          isDefault: false,
        },
      ]

      const result = generateAwsConfig('PROJ_X', accounts)

      expect(result).toContain('[profile PROJ_X-prod]')
      expect(result).toContain('region = us-east-1')
      expect(result).toContain('sso_start_url = https://my-sso.awsapps.com/start')
      expect(result).toContain('sso_region = us-east-1')
      expect(result).toContain('sso_account_id = 987654321098')
      expect(result).toContain('sso_role_name = AdministratorAccess')
    })

    it('should generate config for multiple accounts', () => {
      const accounts: AwsAccount[] = [
        {
          id: 'acc-1',
          name: 'dev',
          region: 'ap-northeast-1',
          accountId: '111111111111',
          auth: { method: 'access_key' },
          isDefault: true,
        },
        {
          id: 'acc-2',
          name: 'prod',
          region: 'us-west-2',
          accountId: '222222222222',
          auth: {
            method: 'sso',
            startUrl: 'https://sso.example.com/start',
            ssoRegion: 'us-east-1',
            permissionSetName: 'ReadOnly',
          },
          isDefault: false,
        },
      ]

      const result = generateAwsConfig('MBC_01', accounts)

      expect(result).toContain('[profile MBC_01-dev]')
      expect(result).toContain('[profile MBC_01-prod]')
      expect(result).toContain('region = ap-northeast-1')
      expect(result).toContain('region = us-west-2')
    })

    it('should use profileName for profile section when available', () => {
      const accounts: AwsAccount[] = [
        {
          id: 'acc-1',
          name: 'Production Account',
          profileName: 'prod',
          region: 'ap-northeast-1',
          accountId: '123456789012',
          auth: { method: 'access_key' },
          isDefault: true,
        },
      ]

      const result = generateAwsConfig('MBC_01', accounts)

      expect(result).toContain('[profile MBC_01-prod]')
      expect(result).not.toContain('[profile MBC_01-Production Account]')
    })

    it('should include comment headers', () => {
      const result = generateAwsConfig('TEST', [])

      const lines = result.split('\n')
      expect(lines[0]).toBe('# Auto-generated by ai-support-agent for project: TEST')
      expect(lines[1]).toBe('# Do not edit manually - this file is overwritten on config sync')
    })

    it('should sanitize values containing newlines to prevent INI injection', () => {
      const accounts: AwsAccount[] = [
        {
          id: 'acc-1',
          name: 'dev',
          region: 'ap-northeast-1\n[profile INJECTED]',
          accountId: '123456789012',
          auth: {
            method: 'sso',
            startUrl: 'https://sso.example.com\r\nevil = true',
            ssoRegion: 'us-east-1\nmalicious = true',
            permissionSetName: 'Admin\r\n[profile evil]',
          },
          isDefault: true,
        },
      ]

      const result = generateAwsConfig('MBC_01', accounts)
      const lines = result.split('\n')

      // Every non-empty, non-comment line should not start with '[' unless it's the profile header
      const dataLines = lines.filter(l => l.trim() && !l.startsWith('#') && !l.startsWith('[profile MBC_01-'))
      for (const line of dataLines) {
        // No line should start a new INI section
        expect(line).not.toMatch(/^\[/)
      }

      // Newlines should be stripped — values should be on a single line each
      const regionLine = lines.find(l => l.startsWith('region = '))
      expect(regionLine).toBe('region = ap-northeast-1[profile INJECTED]')

      const startUrlLine = lines.find(l => l.startsWith('sso_start_url = '))
      expect(startUrlLine).toBe('sso_start_url = https://sso.example.comevil = true')
    })
  })

  describe('writeAwsConfig', () => {
    const projectDir = '/tmp/test-project'
    const awsDir = path.join(projectDir, '.ai-support-agent', 'aws')
    const configPath = path.join(awsDir, 'config')
    const tmpPath = configPath + '.tmp'

    it('should create aws directory if missing and write config atomically', () => {
      mockedFs.existsSync.mockReturnValue(false)
      mockedFs.writeFileSync.mockReturnValue(undefined)
      mockedFs.renameSync.mockReturnValue(undefined)
      mockedFs.mkdirSync.mockReturnValue(undefined)

      const accounts: AwsAccount[] = [
        {
          id: 'acc-1',
          name: 'dev',
          region: 'ap-northeast-1',
          accountId: '123456789012',
          auth: { method: 'access_key' },
          isDefault: true,
        },
      ]

      writeAwsConfig(projectDir, 'MBC_01', accounts)

      expect(mockedFs.mkdirSync).toHaveBeenCalledWith(awsDir, { recursive: true, mode: 0o700 })
      expect(mockedFs.writeFileSync).toHaveBeenCalledWith(
        tmpPath,
        expect.stringContaining('[profile MBC_01-dev]'),
        { mode: 0o600 },
      )
      expect(mockedFs.renameSync).toHaveBeenCalledWith(tmpPath, configPath)
    })

    it('should always call mkdir (recursive) even if aws directory already exists', () => {
      mockedFs.mkdirSync.mockReturnValue(undefined)
      mockedFs.writeFileSync.mockReturnValue(undefined)
      mockedFs.renameSync.mockReturnValue(undefined)

      writeAwsConfig(projectDir, 'MBC_01', [])

      expect(mockedFs.mkdirSync).toHaveBeenCalledWith(awsDir, { recursive: true, mode: 0o700 })
    })

    it('should handle write errors gracefully', () => {
      mockedFs.existsSync.mockReturnValue(true)
      mockedFs.writeFileSync.mockImplementation(() => {
        throw new Error('EACCES: permission denied')
      })

      // Should not throw
      expect(() => writeAwsConfig(projectDir, 'MBC_01', [])).not.toThrow()
    })
  })

  describe('generateAwsCredentials', () => {
    it('should generate credentials without sessionToken', () => {
      const credentialMap = new Map<string, AwsCredentials>([
        [
          'dev',
          {
            accessKeyId: 'AKIAIOSFODNN7EXAMPLE',
            secretAccessKey: 'wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY',
            region: 'ap-northeast-1',
          },
        ],
      ])

      const result = generateAwsCredentials('MBC_01', credentialMap)

      expect(result).toContain('# Auto-generated by ai-support-agent for project: MBC_01')
      expect(result).toContain('[MBC_01-dev]')
      expect(result).toContain('aws_access_key_id = AKIAIOSFODNN7EXAMPLE')
      expect(result).toContain('aws_secret_access_key = wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY')
      expect(result).toContain('region = ap-northeast-1')
      expect(result).not.toContain('aws_session_token')
    })

    it('should generate credentials with sessionToken', () => {
      const credentialMap = new Map<string, AwsCredentials>([
        [
          'staging',
          {
            accessKeyId: 'ASIASAMPLEKEY',
            secretAccessKey: 'secretSample123',
            sessionToken: 'FwoGZXIvYX...tokenValue',
            region: 'us-west-2',
          },
        ],
      ])

      const result = generateAwsCredentials('PROJ_X', credentialMap)

      expect(result).toContain('[PROJ_X-staging]')
      expect(result).toContain('aws_access_key_id = ASIASAMPLEKEY')
      expect(result).toContain('aws_secret_access_key = secretSample123')
      expect(result).toContain('aws_session_token = FwoGZXIvYX...tokenValue')
      expect(result).toContain('region = us-west-2')
    })

    it('should generate credentials for multiple accounts', () => {
      const credentialMap = new Map<string, AwsCredentials>([
        [
          'dev',
          {
            accessKeyId: 'AKIADEV',
            secretAccessKey: 'secretDev',
            region: 'ap-northeast-1',
          },
        ],
        [
          'prod',
          {
            accessKeyId: 'AKIAPROD',
            secretAccessKey: 'secretProd',
            sessionToken: 'prodToken',
            region: 'us-east-1',
          },
        ],
      ])

      const result = generateAwsCredentials('MBC_01', credentialMap)

      expect(result).toContain('[MBC_01-dev]')
      expect(result).toContain('aws_access_key_id = AKIADEV')
      expect(result).toContain('[MBC_01-prod]')
      expect(result).toContain('aws_access_key_id = AKIAPROD')
      expect(result).toContain('aws_session_token = prodToken')
    })

    it('should include comment headers', () => {
      const result = generateAwsCredentials('TEST', new Map())

      const lines = result.split('\n')
      expect(lines[0]).toBe('# Auto-generated by ai-support-agent for project: TEST')
      expect(lines[1]).toBe('# Do not edit manually - this file is overwritten on each chat command')
    })
  })

  describe('writeAwsCredentials', () => {
    const projectDir = '/tmp/test-project'
    const awsDir = path.join(projectDir, '.ai-support-agent', 'aws')
    const credentialsPrefix = path.join(awsDir, 'credentials-')

    beforeEach(() => {
      mockedFs.existsSync.mockReturnValue(false)
      mockedFs.writeFileSync.mockReturnValue(undefined)
      mockedFs.renameSync.mockReturnValue(undefined)
      mockedFs.mkdirSync.mockReturnValue(undefined)
    })

    it('should create aws directory if missing and write credentials atomically to a uniquely-named file', () => {
      const credentialMap = new Map<string, AwsCredentials>([
        [
          'dev',
          {
            accessKeyId: 'AKIATEST',
            secretAccessKey: 'secretTest',
            region: 'ap-northeast-1',
          },
        ],
      ])

      const result = writeAwsCredentials(projectDir, 'MBC_01', credentialMap)

      expect(mockedFs.mkdirSync).toHaveBeenCalledWith(awsDir, { recursive: true, mode: 0o700 })
      // Filename must not be the fixed 'credentials' name — it must carry a
      // random per-call suffix so concurrent chat commands never share a path.
      expect(result).toBeDefined()
      expect(result?.startsWith(credentialsPrefix)).toBe(true)
      expect(result?.slice(credentialsPrefix.length)).toMatch(/^[0-9a-f]{32}$/)

      const tmpPath = `${result}.tmp`
      expect(mockedFs.writeFileSync).toHaveBeenCalledWith(
        tmpPath,
        expect.stringContaining('[MBC_01-dev]'),
        { mode: 0o600 },
      )
      expect(mockedFs.renameSync).toHaveBeenCalledWith(tmpPath, result)
    })

    it('should return a different path on each call (unique per invocation)', () => {
      const credentialMap = new Map<string, AwsCredentials>([
        [
          'dev',
          {
            accessKeyId: 'AKIATEST',
            secretAccessKey: 'secretTest',
            region: 'ap-northeast-1',
          },
        ],
      ])

      const path1 = writeAwsCredentials(projectDir, 'MBC_01', credentialMap)
      const path2 = writeAwsCredentials(projectDir, 'MBC_01', credentialMap)

      expect(path1).toBeDefined()
      expect(path2).toBeDefined()
      expect(path1).not.toBe(path2)
    })

    it('should always call mkdir (recursive) even if aws directory already exists', () => {
      writeAwsCredentials(projectDir, 'MBC_01', new Map())

      expect(mockedFs.mkdirSync).toHaveBeenCalledWith(awsDir, { recursive: true, mode: 0o700 })
    })

    it('should return undefined and not throw on write errors', () => {
      mockedFs.writeFileSync.mockImplementation(() => {
        throw new Error('ENOSPC: no space left on device')
      })

      let result: string | undefined
      expect(() => {
        result = writeAwsCredentials(projectDir, 'MBC_01', new Map())
      }).not.toThrow()
      expect(result).toBeUndefined()
    })

    it('should best-effort delete the leftover .tmp file when renameSync fails after writeFileSync succeeded', () => {
      mockedFs.renameSync.mockImplementation(() => {
        throw new Error('EPERM: operation not permitted, rename')
      })
      mockedFs.rmSync.mockReturnValue(undefined)

      const result = writeAwsCredentials(projectDir, 'MBC_01', new Map())

      expect(result).toBeUndefined()
      const tmpPathArg = (mockedFs.renameSync as jest.Mock).mock.calls[0][0] as string
      expect(tmpPathArg.startsWith(credentialsPrefix)).toBe(true)
      expect(tmpPathArg.endsWith('.tmp')).toBe(true)
      expect(mockedFs.rmSync).toHaveBeenCalledWith(tmpPathArg, { force: true })
    })

    it('should not throw when the best-effort .tmp cleanup itself fails', () => {
      mockedFs.renameSync.mockImplementation(() => {
        throw new Error('EPERM: operation not permitted, rename')
      })
      mockedFs.rmSync.mockImplementation(() => {
        throw new Error('EBUSY: resource busy or locked')
      })

      expect(() => writeAwsCredentials(projectDir, 'MBC_01', new Map())).not.toThrow()
    })

    it('should not attempt .tmp cleanup when the failure happens before a path was generated', () => {
      mockedFs.mkdirSync.mockImplementation(() => {
        throw new Error('EACCES: permission denied')
      })

      const result = writeAwsCredentials(projectDir, 'MBC_01', new Map())

      expect(result).toBeUndefined()
      expect(mockedFs.rmSync).not.toHaveBeenCalled()
    })
  })

  describe('cleanupAwsCredentials', () => {
    // cleanupAwsCredentials now takes the exact absolute path that was
    // written by writeAwsCredentials() for a single call, rather than
    // deriving a fixed <projectDir>/.ai-support-agent/aws/credentials path.
    // This is what makes cleanup safe when multiple chat commands for the
    // same project run concurrently (each writes and cleans up its own
    // uniquely-named file — see writeAwsCredentials above).
    const awsDir = path.join('/tmp/test-project', '.ai-support-agent', 'aws')
    const credentialsPath = path.join(awsDir, 'credentials-aabbccdd112233445566778899aabb0')
    const configPath = path.join(awsDir, 'config')

    it('should delete exactly the given credentials file', () => {
      mockedFs.rmSync.mockReturnValue(undefined)

      cleanupAwsCredentials(credentialsPath)

      expect(mockedFs.rmSync).toHaveBeenCalledWith(credentialsPath, { force: true })
    })

    it('should not delete the config file in the same aws directory', () => {
      mockedFs.rmSync.mockReturnValue(undefined)

      cleanupAwsCredentials(credentialsPath)

      expect(mockedFs.rmSync).not.toHaveBeenCalledWith(configPath, expect.anything())
    })

    it('should best-effort delete the .tmp companion file atomicWriteFile can leave behind on rename failure', () => {
      mockedFs.rmSync.mockReturnValue(undefined)

      cleanupAwsCredentials(credentialsPath)

      expect(mockedFs.rmSync).toHaveBeenCalledWith(`${credentialsPath}.tmp`, { force: true })
    })

    it('should not throw when the credentials file does not exist', () => {
      mockedFs.rmSync.mockImplementation(() => {
        throw new Error('ENOENT: no such file or directory, unlink')
      })

      expect(() => cleanupAwsCredentials(credentialsPath)).not.toThrow()
    })

    it('should not throw when the .tmp companion file does not exist (still attempts the main file)', () => {
      mockedFs.rmSync.mockImplementation((target: fs.PathLike) => {
        if (String(target).endsWith('.tmp')) {
          throw new Error('ENOENT: no such file or directory, unlink')
        }
      })

      expect(() => cleanupAwsCredentials(credentialsPath)).not.toThrow()
      expect(mockedFs.rmSync).toHaveBeenCalledWith(credentialsPath, { force: true })
      expect(mockedFs.rmSync).toHaveBeenCalledWith(`${credentialsPath}.tmp`, { force: true })
    })
  })

  describe('cleanupStaleAwsCredentials', () => {
    // Mirrors cleanupStaleCommandMcpConfigs (mcp/config-writer.ts): because
    // writeAwsCredentials() now writes to a uniquely-named `credentials-*`
    // file per call rather than a fixed shared path, a chat command that is
    // SIGKILLed/OOM-killed before cleanupAwsCredentials() runs leaves a
    // plaintext-AWS-credentials orphan behind forever (no later write ever
    // overwrites it). Sweep old ones on every config sync so they self-heal.
    const awsDir = path.join('/tmp/test-project', '.ai-support-agent', 'aws')
    const oldMs = Date.now() - 25 * 60 * 60 * 1000
    const freshMs = Date.now() - 1000

    function statFor(mtimeMs: number): fs.Stats {
      return { mtimeMs } as fs.Stats
    }

    it('should remove credentials-* files older than maxAgeMs', () => {
      mockedFs.readdirSync.mockReturnValue(['credentials-aaaa1111'] as unknown as fs.Dirent[])
      mockedFs.statSync.mockReturnValue(statFor(oldMs))
      mockedFs.rmSync.mockReturnValue(undefined)

      const removed = cleanupStaleAwsCredentials(awsDir)

      expect(removed).toBe(1)
      expect(mockedFs.rmSync).toHaveBeenCalledWith(path.join(awsDir, 'credentials-aaaa1111'), { recursive: false, force: true })
    })

    it('should also match .tmp companion files left by a failed atomic write', () => {
      mockedFs.readdirSync.mockReturnValue(['credentials-bbbb2222.tmp'] as unknown as fs.Dirent[])
      mockedFs.statSync.mockReturnValue(statFor(oldMs))
      mockedFs.rmSync.mockReturnValue(undefined)

      const removed = cleanupStaleAwsCredentials(awsDir)

      expect(removed).toBe(1)
      expect(mockedFs.rmSync).toHaveBeenCalledWith(path.join(awsDir, 'credentials-bbbb2222.tmp'), { recursive: false, force: true })
    })

    it('should not remove credentials-* files newer than maxAgeMs', () => {
      mockedFs.readdirSync.mockReturnValue(['credentials-cccc3333'] as unknown as fs.Dirent[])
      mockedFs.statSync.mockReturnValue(statFor(freshMs))

      const removed = cleanupStaleAwsCredentials(awsDir)

      expect(removed).toBe(0)
      expect(mockedFs.rmSync).not.toHaveBeenCalled()
    })

    it('should not remove the config file or other unrelated files in the same directory', () => {
      mockedFs.readdirSync.mockReturnValue(['config', 'unrelated-file.txt'] as unknown as fs.Dirent[])
      mockedFs.statSync.mockReturnValue(statFor(oldMs))

      const removed = cleanupStaleAwsCredentials(awsDir)

      expect(removed).toBe(0)
      expect(mockedFs.rmSync).not.toHaveBeenCalled()
    })

    it('should remove all matching files when maxAgeMs=0', () => {
      mockedFs.readdirSync.mockReturnValue(['credentials-dddd4444'] as unknown as fs.Dirent[])
      mockedFs.statSync.mockReturnValue(statFor(freshMs))
      mockedFs.rmSync.mockReturnValue(undefined)

      const removed = cleanupStaleAwsCredentials(awsDir, 0)

      expect(removed).toBe(1)
    })

    it('should return 0 when the directory cannot be read', () => {
      mockedFs.readdirSync.mockImplementation(() => {
        throw new Error('ENOENT: no such file or directory, scandir')
      })

      const removed = cleanupStaleAwsCredentials(awsDir)

      expect(removed).toBe(0)
    })

    it('should ignore individual file removal failures, log a warning, and continue', () => {
      mockedFs.readdirSync.mockReturnValue(['credentials-eeee5555'] as unknown as fs.Dirent[])
      mockedFs.statSync.mockReturnValue(statFor(oldMs))
      mockedFs.rmSync.mockImplementation(() => {
        throw new Error('EBUSY: resource busy or locked')
      })

      const removed = cleanupStaleAwsCredentials(awsDir)

      expect(removed).toBe(0)
      expect(logger.warn).toHaveBeenCalledWith(expect.stringContaining('credentials-eeee5555'))
    })
  })

  describe('buildAwsProfileEnv', () => {
    const projectDir = '/home/user/projects/MBC_01'
    const awsDir = path.join(projectDir, '.ai-support-agent', 'aws')
    const credentialsPath = path.join(awsDir, 'credentials-deadbeefdeadbeefdeadbeefdeadbeef')

    it('should return the fixed config file path and the caller-supplied credentials path', () => {
      const env = buildAwsProfileEnv(projectDir, 'MBC_01', credentialsPath)

      expect(env.AWS_CONFIG_FILE).toBe(path.join(awsDir, 'config'))
      expect(env.AWS_SHARED_CREDENTIALS_FILE).toBe(credentialsPath)
    })

    it('should set AWS_PROFILE when defaultAccountName is provided', () => {
      const env = buildAwsProfileEnv(projectDir, 'MBC_01', credentialsPath, 'dev')

      expect(env.AWS_PROFILE).toBe('MBC_01-dev')
    })

    it('should not set AWS_PROFILE when defaultAccountName is not provided', () => {
      const env = buildAwsProfileEnv(projectDir, 'MBC_01', credentialsPath)

      expect(env.AWS_PROFILE).toBeUndefined()
    })

    it('should not set AWS_PROFILE when defaultAccountName is undefined', () => {
      const env = buildAwsProfileEnv(projectDir, 'MBC_01', credentialsPath, undefined)

      expect(env.AWS_PROFILE).toBeUndefined()
    })

    it('should set AWS_DEFAULT_REGION when defaultRegion is provided', () => {
      const env = buildAwsProfileEnv(projectDir, 'MBC_01', credentialsPath, 'dev', 'ap-northeast-1')

      expect(env.AWS_DEFAULT_REGION).toBe('ap-northeast-1')
    })

    it('should not set AWS_DEFAULT_REGION when defaultRegion is not provided', () => {
      const env = buildAwsProfileEnv(projectDir, 'MBC_01', credentialsPath, 'dev')

      expect(env.AWS_DEFAULT_REGION).toBeUndefined()
    })

    it('should set all environment variables when all parameters are provided', () => {
      const env = buildAwsProfileEnv(projectDir, 'MBC_01', credentialsPath, 'prod', 'us-east-1')

      expect(env).toEqual({
        AWS_CONFIG_FILE: path.join(awsDir, 'config'),
        AWS_SHARED_CREDENTIALS_FILE: credentialsPath,
        AWS_PROFILE: 'MBC_01-prod',
        AWS_DEFAULT_REGION: 'us-east-1',
      })
    })

    it('should use distinct credentials paths for two concurrent calls sharing the same projectDir', () => {
      // Regression test for the parallel-chat-commands race: two calls for the
      // same project must never resolve to the same AWS_SHARED_CREDENTIALS_FILE.
      const pathA = path.join(awsDir, 'credentials-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa')
      const pathB = path.join(awsDir, 'credentials-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb')

      const envA = buildAwsProfileEnv(projectDir, 'MBC_01', pathA, 'dev')
      const envB = buildAwsProfileEnv(projectDir, 'MBC_01', pathB, 'dev')

      expect(envA.AWS_SHARED_CREDENTIALS_FILE).not.toBe(envB.AWS_SHARED_CREDENTIALS_FILE)
    })
  })
})
